# Site Info
title:              "principia vitae"
description:        "Writings in AI, deep learning, intelligence, and MIT."
google_verify:      HdgB206sJq6STy2hJJTmWDunWz8vq2wd_DueQdr-7EM
google_analytics:   UA-85438373-1 # Put your Google Analytics code

# Author Info
author_name:        "Surya Bhupatiraju"
author_email:       surya@mit.edu
author_gravatar:    ae2220d52b21a6a3521843df6f97a8ae# Gravatar md5 hash
twitter_username:   suryabhupa

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /notes/:title # Post permalink
timezone:           America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
highlighter:        rouge
#markdown:           redcarpet
#redcarpet:
#    extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
